language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abhibajaj/docker-react -f Dockerfile.dev ./

script:
  - docker run -e CI=true abhibajaj/docker-react yarn run test
